[package]
name = "bulletproof_rangeproof"
version = "0.1.0"
edition = "2024"

[dependencies]
bulletproofs = "4.0.0"
curve25519-dalek-ng = "4.0"
merlin = "3.0.0"
rand = "0.8"
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
